# base terraform workflow using super-linter to enforce linting
name: linter-terraform-please-work

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    name: Lint Terraform Base
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # apparently super-linter only tflints and does not tf fmt
      - name: Terraform Format Check
        run: terraform fmt -recursive -check -diff

      - name: Super-Linter
        uses: github/super-linter/slim@v4
        env:
          SUPPRESS_POSSUM: true
          LOG_LEVEL: NOTICE
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_TERRAFORM: true
          VALIDATE_YAML: true
          VALIDATE_EDITORCONFIG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
